# Generated by Django 4.1.3 on 2022-11-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='disco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=250, verbose_name='Descrição')),
                ('selo_fonografico', models.CharField(max_length=50)),
                ('ano', models.DateField()),
                ('pais', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50, verbose_name='')),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
